---
 - name: transfer zabbix install package to remote host and unarchive to /tmp/
   unarchive:
    src: ../../../packages/zabbix/{{mtls_zabbix}}
    dest: /tmp/
    owner: zabbix
    group: zabbix

 - name: transfer install script to remonte host
   template: 
    src: ../template/install_zabbix_server.sh
    dest: /tmp/install_zabbix_server.sh

 - name: install zabbix_server_node
   shell: bash /tmp/install_zabbix_server.sh

 - name: copy zabbix web-site file to /usr/local/httpd/htdocs/
   shell: cp -rf /tmp/{{mtls_zabbix | replace('.tar.gz','')}}/frontends/php/* /usr/local/httpd/htdocs/

 - name: change /usr/local/httpd/htdocs/ owner and group
   file:
    path: /usr/local/httpd/htdocs
    owner: daemon
    group: daemon
    recurse: yes

 - name: change owner to zabbix user
   file:
    path: /usr/local/{{mtls_zabbix | replace('.tar.gz','')}}
    owner: zabbix
    group: zabbix
    recurse: yes

 - name: make link
   file:
    src: /usr/local/{{mtls_zabbix | replace('.tar.gz','')}}
    dest: /usr/local/zabbix
    state: link
    owner: zabbix
    group: zabbix

 - name: transfer zabbix server config file to remonte host
   template:
    src: ../template/zabbix_server.conf
    dest: /usr/local/zabbix/etc/zabbix_server.conf
    owner: zabbix
    group: zabbix

 - name: transfer zabbix agent config file to remonte host
   template:
    src: ../template/zabbix_agent.conf
    dest: /usr/local/zabbix/etc/zabbix_agentd.conf
    owner: zabbix
    group: zabbix

 - name: transfer zabbix database init script to remonte host
   template:
    src: template/init_zabbix_database.sql
    dest: /tmp/init_zabbix_database.sql

 - name: init zabbix database
   shell: mysql -uroot -p{{mysql_root_password}}  < /tmp/init_zabbix_database.sql
   

 - name: remove /tmp/install_zabbix_server.sh 
   file:
    dest: /tmp/install_zabbix_server.sh 
    state: absent

 - name: remove /tmp/{{mtls_zabbix | replace('.tar.gz','')}}
   file:
    dest: /tmp/{{mtls_zabbix | replace('.tar.gz','')}}
    state: absent

 - name: remove /tmp/init_zabbix_database.sql
   file:
    dest: /tmp/init_zabbix_database.sql
    state: absent

 - name: export path env variable
   lineinfile:
    path: /etc/profile
    line: export PATH=/usr/local/zabbix/bin/:$PATH
    insertafter: EOF

 - name: export path env to /root/.bashrc
   lineinfile:
    path: /root/.bashrc
    line: export PATH=/usr/local/zabbix/bin/:$PATH
    insertafter: EOF  



 