---
 - hosts: sqlstudio
   remote_user: root
   become_user: root
   vars_files:
    - ../../../config.yaml
   tasks:
    - name: create user and config file
      import_tasks: common/create_user_and_config_file.yaml

    - name: install mysql dependents 
      import_tasks: common/install_mysql_dependents.yaml

    - name: install mysql to /usr/local/mysql
      import_tasks: common/install_mysql.yaml

    - name: init mysql datadir
      import_tasks: common/initialize_mysql_datadir.yaml

    - name: config mysql service and start mysql
      import_tasks: common/config_mysql_service_and_start_mysql.yaml

    - name: sleep 15's
      shell: sleep 15

    - name: make mysql secure
      import_tasks: common/make_mysql_security.yaml
...
