---
 - hosts: uwsgiweb
   remote_user: root
   become_user: root
   vars_files:
    - ../../../config.yaml
   tasks:
    - name: install dependents
      import_tasks: ./common/install_dependents.yaml
    
    - name: install nginx
      import_tasks: ./common/install_nginx.yaml
    
