master_ip: "10.186.19.17"

slave_ips:
 - "10.186.19.18"
 - "10.186.19.19"

schemas:
 - "appdb"
 - "blogdb"

# - "mysql"
# - "information-schema"
# - "performance-schema"
# - "sys"
# ------------------------------------------------