---
 - hosts: sqlstudio
   remote_user: root
   become_user: root
   vars_files:
    - ../../../config.yaml
   tasks:
    - name: add zabbix user to system
      user:
       name: zabbix
       state: present

    - import_tasks: common/install_dependents.yaml

    - import_tasks: common/install_agent_node.yaml

    - import_tasks: common/config_monitor_script.yaml 

    - import_tasks: common/config_zabbix_agent_service.yaml

    


