---
 - hosts: cstudio
   remote_user: root
   become_user: root
   vars_files:
    - ../../../config.yaml
    - vars/var_mycat.yaml 

   tasks:
    - name: install dependents
      import_tasks: common/install_dependents.yaml
      
    - name: install mycat
      import_tasks: common/install_mycat.yaml

    - name: start mycat
      import_tasks: common/start_mycat.yaml
